apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-olivetti-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-olivetti
  template:
    metadata:
      labels:
        app: mlops-olivetti
    spec:
      containers:
      - name: mlops-olivetti
        image: akash840/mlops-olivetti:dev
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-olivetti-service
spec:
  selector:
    app: mlops-olivetti
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
